// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbdyzcxrhwpkmgbruimm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiZHl6Y3hyaHdwa21nYnJ1aW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzYwMzAsImV4cCI6MjA2MTg1MjAzMH0.kGlqsx13_u1LQGWvkSDUfg_BceSOK16vbfStzVvUx1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);